# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtLt7V9RQve9aZ1GG5N2TIxONJkRD_sx
"""

try:
    with open("sample.txt", "r") as file:
        reading_file = file.read()
        print(reading_file)
except FileNotFoundError:
    print("The file doesn't exist.")

file = open("sample.txt", "r")
reading_file = file.read()
print(reading_file)