# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5fg7DS7HSahXirn6PQszh-5OxRn7cfc
"""

user_input = input("Enter some text to write to the file: ")
with open("output.txt", "w") as file:
    file.write(user_input + "\n")
additional_input = input("Enter more text to append to the file: ")
with open("output.txt", "a") as file:
    file.write(additional_input + "\n")
print("\nFinal content of output.txt:")
with open("output.txt", "r") as file:
    for line in file:
        print(line.strip())